
// --------------------------------------------------------------------------------
/// <summary>
/// layout.tsx
/// project
/// created by Mehrdad Soleimanimajd on 29.05.2023
/// </summary>
/// <created>ʆϒʅ, 29.05.2023</created>
/// <changed>ʆϒʅ, 31.05.2023</changed>
// --------------------------------------------------------------------------------


import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'wonderful next App!',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
